name: Legacy Build, Test and Publish
# This workflow is being replaced by the new CI/CD pipeline in ci.yml and changesets.yml
# It is kept here for reference and will be removed in a future update

on:
  workflow_dispatch:

jobs:
  redirect:
    name: Redirect to New Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Notify about workflow change
        run: |
          echo "This workflow is deprecated. Please use the new CI/CD pipeline in ci.yml instead."
          echo "The new workflow includes:"
          echo "- Improved caching and artifact sharing"
          echo "- Parallel testing with sharding"
          echo "- Automated semantic versioning with Changesets"
          echo "- Documentation automation"

      - name: Trigger new workflow
        run: |
          echo "Triggering the new CI/CD workflow..."
          gh workflow run "CI/CD Pipeline" -R ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
