name: Unit and E2E Tests

on:
  workflow_call:
    outputs:
      unit_tests_result:
        description: 'Result of the unit tests'
        value: ${{ jobs.unit-tests.outputs.result }}
      e2e_tests_result:
        description: 'Result of the E2E tests'
        value: ${{ jobs.e2e-tests.outputs.result }}
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tests-build-artifacts
          path: dist/
          retention-days: 1

  unit-tests:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-latest
    outputs:
      result: ${{ job.status }}
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: tests-build-artifacts

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Vitest
        run: yarn test:unit:shard ${{ matrix.shard }}/4 --run

  e2e-tests:
    name: E2E Tests
    needs: build
    runs-on: ubuntu-latest
    outputs:
      result: ${{ job.status }}
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: tests-build-artifacts

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright browsers (headless mode)
        run: |
          yarn playwright install --with-deps
          echo "Using headless browser mode for CI/CD"

      - name: Run E2E tests
        run: yarn playwright test tests/e2e --shard=${{ matrix.shard }}/2
        env:
          # Ensure headless mode is used
          PLAYWRIGHT_HEADLESS: true

      - name: Upload E2E test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.shard }}
          path: playwright-report/
          retention-days: 7
