name: Unit Tests

on:
  # Allow manual triggering
  workflow_dispatch:
  # Allow this workflow to be called by other workflows
  workflow_call:
    outputs:
      result:
        description: 'Result of the unit tests'
        value: ${{ jobs.unit-tests.outputs.result }}

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    outputs:
      result: ${{ job.status }}
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the app
        run: yarn build

      - name: Run Vitest
        run: yarn test:unit:shard ${{ matrix.shard }}/4 --run
